# Generated by Django 5.2 on 2026-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product Title')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regular Price')),
                ('promo_price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo Price')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vendor')),
                ('product_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Code (SKU)')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('memory', models.CharField(blank=True, max_length=100, null=True, verbose_name='Memory')),
                ('reviews_count', models.IntegerField(blank=True, null=True, verbose_name='Reviews Count')),
                ('screen_diagonal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Screen Diagonal')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Screen Resolution')),
                ('image_urls', models.JSONField(blank=True, default=list, null=True, verbose_name='Image Gallery URLs')),
                ('specifications', models.JSONField(blank=True, default=dict, null=True, verbose_name='Detailed Specifications')),
                ('link', models.URLField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Product Page Link')),
                ('status', models.CharField(blank=True, default='New', max_length=50, null=True, verbose_name='Processing Status')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Scraped At')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ('id',),
            },
        ),
    ]
