# Generated by Django 5.2 on 2026-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated At'),
        ),
    ]
